export const options = [
  { id: 1, value: "AUS", label: " Австралия" },
  { id: 2, value: "AUT", label: " Австрия" },
  { id: 3, value: "AZE", label: " Азербайджан" },
  { id: 4, value: "ALB", label: " Албания" },
  { id: 5, value: "DZA", label: " Алжир" },
  { id: 6, value: "VIR", label: " Американские Виргинские острова" },
  { id: 7, value: "ASM", label: " Американское Самоа" },
  { id: 8, value: "AIA", label: " Ангилья" },
  { id: 9, value: "AGO", label: " Ангола" },
  { id: 10, value: "AND", label: " Андорра" },
  { id: 11, value: "ATA", label: " Антарктида" },
  { id: 12, value: "ATG", label: " Антигуа и Барбуда" },
  { id: 13, value: "ARG", label: " Аргентина" },
  { id: 14, value: "ARM", label: " Армения" },
  { id: 15, value: "ABW", label: " Аруба" },
  { id: 16, value: "AFG", label: " Афганистан" },
  { id: 17, value: "BHS", label: " Багамские острова" },
  { id: 18, value: "BGD", label: " Бангладеш" },
  { id: 19, value: "BRB", label: " Барбадос" },
  { id: 20, value: "BHR", label: " Бахрейн" },
  { id: 21, value: "BLZ", label: " Белиз" },
  { id: 22, value: "BLR", label: " Белоруссия" },
  { id: 23, value: "BEL", label: " Бельгия" },
  { id: 24, value: "BEN", label: " Бенин" },
  { id: 25, value: "BMU", label: " Бермуды" },
  { id: 26, value: "BGR", label: " Болгария" },
  { id: 27, value: "BOL", label: " Боливия" },
  { id: 28, value: "BES", label: " Бонайре, Синт-Эстатиус и Саба" },
  { id: 29, value: "BIH", label: " Босния и Герцеговина" },
  { id: 30, value: "BWA", label: " Ботсвана" },
  { id: 31, value: "BRA", label: " Бразилия" },
  { id: 32, value: "IOT", label: " Британская территория в Индийском океане" },
  { id: 33, value: "VGB", label: " Британские Виргинские острова" },
  { id: 34, value: "BRN", label: " Бруней" },
  { id: 35, value: "BVT", label: " Буве" },
  { id: 36, value: "BFA", label: " Буркина-Фасо" },
  { id: 37, value: "BDI", label: " Бурунди" },
  { id: 38, value: "BTN", label: " Бутан" },
  { id: 39, value: "VUT", label: " Вануату" },
  { id: 40, value: "VAT", label: " Ватикан" },
  { id: 41, value: "GBR", label: " Великобритания" },
  { id: 42, value: "HUN", label: " Венгрия" },
  { id: 43, value: "VEN", label: " Венесуэла" },
  { id: 44, value: "TLS", label: " Восточный Тимор (Тимор-Лешти)" },
  { id: 45, value: "VNM", label: " Вьетнам" },
  { id: 46, value: "GAB", label: " Габон" },
  { id: 47, value: "HTI", label: " Гаити" },
  { id: 48, value: "GUY", label: " Гайана" },
  { id: 49, value: "GMB", label: " Гамбия" },
  { id: 50, value: "GHA", label: " Гана" },
  { id: 51, value: "GLP", label: " Гваделупа" },
  { id: 52, value: "GTM", label: " Гватемала" },
  { id: 53, value: "GIN", label: " Гвинея" },
  { id: 54, value: "GNB", label: " Гвинея-Бисау" },
  { id: 55, value: "DEU", label: " Германия" },
  { id: 56, value: "GGY", label: " Гернси" },
  { id: 57, value: "GIB", label: " Гибралтар" },
  { id: 58, value: "HND", label: " Гондурас" },
  { id: 59, value: "HKG", label: " Гонконг" },
  { id: 60, value: "GRD", label: " Гренада" },
  { id: 61, value: "GRL", label: " Гренландия" },
  { id: 62, value: "GRC", label: " Греция" },
  { id: 63, value: "GEO", label: " Грузия" },
  { id: 64, value: "GUM", label: " Гуам" },
  { id: 65, value: "DNK", label: " Дания" },
  { id: 66, value: "COD", label: " Демократическая Республика Конго" },
  { id: 67, value: "JEY", label: " Джерси" },
  { id: 68, value: "DJI", label: " Джибути" },
  { id: 69, value: "DMA", label: " Доминика" },
  { id: 70, value: "DOM", label: " Доминикана" },
  { id: 71, value: "EGY", label: " Египет" },
  { id: 72, value: "ZMB", label: " Замбия" },
  {
    id: 73,
    value: "ESH",
    label: " Западная Сахара (Сахарская Арабская Демократическая Республика)",
  },
  { id: 74, value: "ZWE", label: " Зимбабве" },
  { id: 75, value: "ISR", label: " Израиль" },
  { id: 76, value: "IND", label: " Индия" },
  { id: 77, value: "IDN", label: " Индонезия" },
  { id: 78, value: "JOR", label: " Иордания" },
  { id: 79, value: "IRQ", label: " Ирак" },
  { id: 80, value: "IRN", label: " Иран" },
  { id: 81, value: "IRL", label: " Ирландия" },
  { id: 82, value: "ISL", label: " Исландия" },
  { id: 83, value: "ESP", label: " Испания" },
  { id: 84, value: "ITA", label: " Италия" },
  { id: 85, value: "YEM", label: " Йемен" },
  { id: 86, value: "CPV", label: " Кабо-Верде (Острова Зеленого Мыса)" },
  { id: 87, value: "KAZ", label: " Казахстан" },
  { id: 88, value: "CYM", label: " Каймановы острова" },
  { id: 89, value: "KHM", label: " Камбоджа" },
  { id: 90, value: "CMR", label: " Камерун" },
  { id: 91, value: "CAN", label: " Канада" },
  { id: 92, value: "QAT", label: " Катар" },
  { id: 93, value: "KEN", label: " Кения" },
  { id: 94, value: "CYP", label: " Кипр" },
  { id: 95, value: "KGZ", label: " Киргизия" },
  { id: 96, value: "KIR", label: " Кирибати" },
  { id: 97, value: "CHN", label: " Китай" },
  { id: 98, value: "PRK", label: " КНДР" },
  { id: 99, value: "CCK", label: " Кокосовые острова (Килинг)" },
  { id: 100, value: "COL", label: " Колумбия" },
  { id: 101, value: "COM", label: " Коморские острова" },
  { id: 102, value: "KOR", label: " Корея" },
  { id: 103, value: "", label: " Косово" },
  { id: 104, value: "CRI", label: " Коста-Рика" },
  { id: 105, value: "CIV", label: " Кот-д’Ивуар (Берег Слоновой Кости)" },
  { id: 106, value: "CUB", label: " Куба" },
  { id: 107, value: "KWT", label: " Кувейт" },
  { id: 108, value: "CUW", label: " Кюрасао" },
  { id: 109, value: "LAO", label: " Лаос" },
  { id: 110, value: "LVA", label: " Латвия" },
  { id: 111, value: "LSO", label: " Лесото" },
  { id: 112, value: "LBR", label: " Либерия" },
  { id: 113, value: "LBN", label: " Ливан" },
  { id: 114, value: "LBY", label: " Ливия" },
  { id: 115, value: "LTU", label: " Литва" },
  { id: 116, value: "LIE", label: " Лихтенштейн" },
  { id: 117, value: "LUX", label: " Люксембург" },
  { id: 118, value: "MUS", label: " Маврикий" },
  { id: 119, value: "MRT", label: " Мавритания" },
  { id: 120, value: "MDG", label: " Мадагаскар" },
  { id: 121, value: "MYT", label: " Майотта" },
  { id: 122, value: "MAC", label: " Макао (Аомынь)" },
  { id: 123, value: "MKD", label: " Македония" },
  { id: 124, value: "MWI", label: " Малави" },
  { id: 125, value: "MYS", label: " Малайзия" },
  { id: 126, value: "MLI", label: " Мали" },
  { id: 127, value: "MDV", label: " Мальдивы" },
  { id: 128, value: "MLT", label: " Мальта" },
  { id: 129, value: "MAR", label: " Марокко" },
  { id: 130, value: "MTQ", label: " Мартиника" },
  { id: 131, value: "MHL", label: " Маршалловы острова" },
  { id: 132, value: "MEX", label: " Мексика" },
  { id: 133, value: "", label: " Мелилья" },
  { id: 134, value: "MOZ", label: " Мозамбик" },
  { id: 135, value: "MDA", label: " Молдавия" },
  { id: 136, value: "MCO", label: " Монако" },
  { id: 137, value: "MNG", label: " Монголия" },
  { id: 138, value: "MSR", label: " Монтсеррат" },
  { id: 139, value: "MMR", label: " Мьянма (Бирма)" },
  { id: 140, value: "", label: " Нагорно-Карабахская Республика" },
  { id: 141, value: "NAM", label: " Намибия" },
  { id: 142, value: "NRU", label: " Науру" },
  { id: 143, value: "NPL", label: " Непал" },
  { id: 144, value: "NER", label: " Нигер" },
  { id: 145, value: "NGA", label: " Нигерия" },
  { id: 146, value: "ANT", label: " Нидерландские Антильские острова" },
  { id: 147, value: "NLD", label: " Нидерланды (Голландия)" },
  { id: 148, value: "NIC", label: " Никарагуа" },
  { id: 149, value: "NIU", label: " Ниуэ" },
  { id: 150, value: "NZL", label: " Новая Зеландия" },
  { id: 151, value: "NCL", label: " Новая Каледония" },
  { id: 152, value: "NOR", label: " Норвегия" },
  { id: 153, value: "ARE", label: " ОАЭ" },
  { id: 154, value: "OMN", label: " Оман" },
  { id: 155, value: "NFK", label: " Остров Норфолк" },
  { id: 156, value: "CXR", label: " Остров Рождества" },
  { id: 157, value: "SHN", label: " Остров Святой Елены" },
  { id: 158, value: "HMD", label: " Остров Херд и острова Макдональд" },
  { id: 159, value: "COK", label: " Острова Кука" },
  { id: 160, value: "PCN", label: " Острова Питкэрн" },
  { id: 161, value: "TCA", label: " Острова Тёркс и Кайкос" },
  { id: 162, value: "WLF", label: " Острова Уоллис и Футуна" },
  { id: 163, value: "PAK", label: " Пакистан" },
  { id: 164, value: "PLW", label: " Палау" },
  { id: 165, value: "PSE", label: " Палестина" },
  { id: 166, value: "PAN", label: " Панама" },
  { id: 167, value: "PNG", label: " Папуа — Новая Гвинея" },
  { id: 168, value: "PRY", label: " Парагвай" },
  { id: 169, value: "PER", label: " Перу" },
  { id: 170, value: "POL", label: " Польша" },
  { id: 171, value: "PRT", label: " Португалия" },
  { id: 172, value: "", label: " Приднестровье" },
  { id: 173, value: "PRI", label: " Пуэрто-Рико" },
  { id: 174, value: "COG", label: " Республика Конго" },
  { id: 175, value: "REU", label: " Реюньон" },
  { id: 176, value: "RUS", label: " Россия" },
  { id: 177, value: "RWA", label: " Руанда" },
  { id: 178, value: "ROU", label: " Румыния" },
  { id: 179, value: "SLV", label: " Сальвадор" },
  { id: 180, value: "WSM", label: " Самоа" },
  { id: 181, value: "SMR", label: " Сан-Марино" },
  { id: 182, value: "STP", label: " Сан-Томе и Принсипи" },
  { id: 183, value: "SAU", label: " Саудовская Аравия" },
  { id: 184, value: "MNP", label: " Северные Марианские острова" },
  { id: 185, value: "", label: " Северный Кипр" },
  { id: 186, value: "SYC", label: " Сейшелы" },
  { id: 187, value: "SPM", label: " Сен-Пьер и Микелон" },
  { id: 188, value: "SEN", label: " Сенегал" },
  { id: 189, value: "VCT", label: " Сент-Винсент и Гренадины" },
  { id: 190, value: "KNA", label: " Сент-Китс и Невис" },
  { id: 191, value: "LCA", label: " Сент-Люсия" },
  { id: 192, value: "SRB", label: " Сербия" },
  { id: 193, value: "", label: " Сеута" },
  { id: 194, value: "SGP", label: " Сингапур" },
  { id: 195, value: "SYR", label: " Сирия" },
  { id: 196, value: "SVK", label: " Словакия" },
  { id: 197, value: "SVN", label: " Словения" },
  { id: 198, value: "SLB", label: " Соломоновы острова" },
  { id: 199, value: "SOM", label: " Сомали" },
  { id: 200, value: "SDN", label: " Судан" },
  { id: 201, value: "SUR", label: " Суринам" },
  { id: 202, value: "USA", label: " США" },
  { id: 203, value: "SLE", label: " Сьерра-Леоне" },
  { id: 204, value: "TJK", label: " Таджикистан" },
  { id: 205, value: "THA", label: " Таиланд" },
  { id: 206, value: "TWN", label: " Тайвань" },
  { id: 207, value: "TZA", label: " Танзания" },
  { id: 208, value: "TGO", label: " Того" },
  { id: 209, value: "TKL", label: " Токелау" },
  { id: 210, value: "TON", label: " Тонга" },
  { id: 211, value: "TTO", label: " Тринидад и Тобаго" },
  { id: 212, value: "TUV", label: " Тувалу" },
  { id: 213, value: "TUN", label: " Тунис" },
  { id: 214, value: "TKM", label: " Туркмения" },
  { id: 215, value: "TUR", label: " Турция" },
  { id: 216, value: "UGA", label: " Уганда" },
  { id: 217, value: "UZB", label: " Узбекистан" },
  { id: 218, value: "UKR", label: " Украина" },
  { id: 219, value: "URY", label: " Уругвай" },
  { id: 220, value: "FRO", label: " Фарерские острова" },
  { id: 221, value: "FSM", label: " Федеративные Штаты Микронезии" },
  { id: 222, value: "FJI", label: " Фиджи" },
  { id: 223, value: "PHL", label: " Филиппины" },
  { id: 224, value: "FIN", label: " Финляндия" },
  { id: 225, value: "FLK", label: " Фолклендские (Мальвинские) острова" },
  { id: 226, value: "FRA", label: " Франция" },
  { id: 227, value: "GUF", label: " Французская Гвиана" },
  { id: 228, value: "PYF", label: " Французская Полинезия (Таити)" },
  {
    id: 229,
    value: "ATF",
    label: " Французские Южные и Антарктические Территории",
  },
  { id: 230, value: "HRV", label: " Хорватия" },
  { id: 231, value: "CAF", label: " Центральноафриканская Республика" },
  { id: 232, value: "TCD", label: " Чад" },
  { id: 233, value: "MNE", label: " Черногория" },
  { id: 234, value: "CZE", label: " Чехия" },
  { id: 235, value: "CHL", label: " Чили" },
  { id: 236, value: "FSM", label: " Чуук (Трук)" },
  { id: 237, value: "CHE", label: " Швейцария" },
  { id: 238, value: "SWE", label: " Швеция" },
  { id: 239, value: "SJM", label: " Шпицберген и Ян-Майен" },
  { id: 240, value: "LKA", label: " Шри-Ланка (Цейлон)" },
  { id: 241, value: "ECU", label: " Эквадор" },
  { id: 242, value: "GNQ", label: " Экваториальная Гвинея" },
  { id: 243, value: "ERI", label: " Эритрея" },
  { id: 244, value: "SWZ", label: " Эсватини (Свазиленд)" },
  { id: 245, value: "EST", label: " Эстония" },
  { id: 246, value: "ETH", label: " Эфиопия" },
  { id: 247, value: "ZAF", label: " ЮАР" },
  { id: 248, value: "SGS", label: " Южная Георгия и Южные Сандвичевы острова" },
  { id: 251, value: "JAM", label: " Ямайка" },
  { id: 252, value: "FSM", label: " Яп" },
  { id: 253, value: "JPN", label: " Япония" },
];
